apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-music-pvc
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn