replicaCount: 1

image:
  repository: cbartram/spotify-plex-sync
  pullPolicy: IfNotPresent
  tag: "latest"

namespace: plex

podAnnotations: {}
podLabels:
  app: spotify-plex-sync

nodeSelector:
  kubernetes.io/hostname: ip-192-168-86-33

tolerations: []
affinity: {}

containerPort: 8000

env:
  musicDir: /music
  staticDir: /app/static

volumes:
  music:
    mountPath: /music
    existingPvc: plex-music-pvc

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

podSecurityContext:
 fsGroup: 2000

livenessProbe:
 httpGet:
   path: /health
   port: web
 initialDelaySeconds: 30
 periodSeconds: 10

readinessProbe:
 httpGet:
   path: /health
   port: web
 initialDelaySeconds: 3
 periodSeconds: 5
