apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-plex-sync
  namespace: {{ .Values.namespace }}
  labels:
    app: spotify-plex-sync
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: spotify-plex-sync
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app: spotify-plex-sync
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: main
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
          name: web
          protocol: TCP
        env:
        - name: MUSIC_DIR
          value: {{ .Values.env.musicDir | quote }}
        - name: SPOTDL_PATH
          value: {{ .Values.env.spotdlPath | quote }}
        - name: STATIC_DIR
          value: {{ .Values.env.staticDir | quote }}
        - name: COOKIES_FILE
          value: {{ .Values.env.cookiesFile | quote }}
        - name: SPOTIFY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: spotify-plex-sync-secrets
              key: CLIENT_ID
        - name: SPOTIFY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
                name: spotify-plex-sync-secrets
                key: CLIENT_SECRET
        volumeMounts:
        - name: music-library
          mountPath: {{ .Values.volumes.music.mountPath }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: music-library
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.music.existingPvc }}